// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgqhwtkwvzbsktsblseq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncWh3dGt3dnpic2t0c2Jsc2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQ1MDYsImV4cCI6MjA3MTExMDUwNn0.eNfZj2lj4zMT6sLhiQfeyaPE-sW9hmIwjLxftCNkg4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});